### ISSUE TITLE
BUG: Medic's ubercharge percentage

### ISSUE THREAD

**Issue by JustCallMeQuincy** [PapaPeach/xhud#5]
Using pretty much default settings.

Medic's ubercharge percentage has - what I assume - a wrong calculation in it.

![image](https://user-images.githubusercontent.com/71931404/218342646-0bf95f0c-d086-473f-81e0-55573fdfb03e.png)

It may have a `*100` too much or something like that.

**Comment by PapaPeach** [comment]
It is not a calculation error. The uber charge font only allows non-letter characters in it, in order to have the uber/kritz/vacc/quickfix icons. Your medic probably had a medi gun name like "Medi Gun 2" and was at 73% charge, so it displayed as "273%".

There's not really a good way around this but in recent updates to the dev build I'm testing adding a gap between the medi gun name and charge % to at least make the numbers separated enough to be clearly different.

**Comment by JustCallMeQuincy** [comment]
Oh alright, that's such a strange issue haha.

Thanks for checking out how to fix the issue!
