### ISSUE TITLE
Feature request: MvM broken updates

### ISSUE THREAD

**Issue by JustCallMeQuincy** [PapaPeach/xhud#6]
**Description.**
To add hints or grayed-out tick-boxes over the broken/bugged MvM upgrades, to inform of them (maybe the ability to toggle it through the customization menu?).

(This guide has a nice list: https://steamcommunity.com/sharedfiles/filedetails/?id=2186734894)

**Comment by PapaPeach** [comment]
I don't think the implementation you suggested is possible as you can't define HUD elements for individual weapon/upgrades. You can only really edit the "template" the game uses for every upgrade. The best foreseeable implementation of this would be a list of broken upgrades on the side of the screen. I'll consider it but I wouldn't count on it since that would be unappealing and is mostly understood after a few tours.
